import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Header, Navbar, Footer } from "@/components/common"

const roboto = Roboto({ weight: ['300', '400', '500', '700', '900'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BİMcell',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="tr">
      <body className={`${roboto.className} bg-bg-body`}>
        <Header />
        <Navbar />
        <main>
          {children}
        </main>        
        <Footer />
      </body>
    </html>
  )
}
